### ISSUE TITLE
qt has been merged switch 

### ISSUE THREAD

**Issue by cordoval** [michaelperrin/docker-wkhtmltopdf#1]
https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz is broken

no longer valid

**Comment by michaelperrin** [comment]
It works for me. It was probably a temporary issue. Can you confirm the issue?

**Comment by cordoval** [comment]
too late, is this still needed? i noticed the original site has now the qt and all, and with the same version, can you confirm please?

i think the url i was trying that time was gna.org or something like that, so different

**Comment by michaelperrin** [comment]
There is a so-called "bleeding edge" version that uses a newer version of Qt, but it seems abandoned.

**Comment by cordoval** [comment]
really?
are you sure? https://github.com/michaelperrin/docker-wkhtmltopdf/blob/master/Dockerfile#L14 that was the broken link i got before

but check

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.4

it says it has already qt in since 0.12.2 or 0.12.3 i think no?

**Comment by michaelperrin** [comment]
You are right concerning the path. This is now fixed (thanks for pointing this out!).
I didn't get what you are referring to concerning Qt. It does use it internally indeed.

**Comment by cordoval** [comment]
👴 thanks
