### ISSUE TITLE
The download link is wrong. It does not exists anymore.

### ISSUE THREAD

**Issue by osamaeshtiaq** [michaelperrin/docker-wkhtmltopdf#3]
Running command
RUN curl "https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz" -L -o "wkhtmltopdf.tar.xz"
Gives the following error.

The command '/bin/sh -c curl "https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz" -L -o "wkhtmltopdf.tar.xz"' returned a non-zero code: 6

**Comment by michaelperrin** [comment]
Thank you for opening this issue @osamaeshtiaq . I have now updated the Docker image and fixed the download link.
